### ISSUE TITLE
Sorting in workflow list does not work (or at least not in an understandable way)

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#16] opened 2013-08-26 07:59 UTC
When clicking on a column, an arrow appear. further clöicking resorts the list, but not according to the column. Clicking on lastUpdate seems to sort the rest of the table, but the lastUpdateColumn did not change (maybe not reproducible, but this happened some minutes before...)

**Comment by kba** [comment] 2013-09-23 10:06
Indeed, I cannot reproduce this.

Clicking on a column title will sort the column alphanumerically by the value in there. "lastUpdated" should be sorted by the date in Iso8601 format but still display the human-readable date.

Maybe the table should by default be sorted by lastUpdated, as should be the file list (#18)

**Comment by kba** [comment] 2013-09-23 11:12
Fixed by  https://github.com/DM2E/dm2e-gui/commit/cda85a81984af12490f540b513543efc53603ed7

**Comment by kba** [comment] 2013-09-23 14:27
Bug in sorttable.js in Firefox:
TypeError: m is undefined
http://omnom.hu-berlin.de/vendor/sorttable.js
Line 276

**Closed as completed** 2013-09-24 19:55 UTC
Labels: bug
